import { readFileSync, writeFileSync } from 'node:fs';

const contract = JSON.parse(readFileSync(new URL('../docs/swagger.json', import.meta.url), 'utf8'));
const output = new URL('../docs/redoc.html', import.meta.url);
const title = contract.info.title.replace(/[&<>"']/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[character]));

// Escape HTML delimiters so specification text cannot terminate the embedded JSON script.
const specification = JSON.stringify(contract).replace(/[<>&\u2028\u2029]/g,
  (character) => `\\u${character.charCodeAt(0).toString(16).padStart(4, '0')}`);

writeFileSync(output, `<!DOCTYPE html>
<!-- Generated by make redoc; update the OpenAPI annotations instead of this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style>body { margin: 0; padding: 0; }</style>
</head>
<body>
  <div id="redoc"></div>
  <script id="openapi" type="application/json">${specification}</script>
  <script src="https://cdn.redocly.com/redoc/v2.5.4/bundles/redoc.standalone.js"
    integrity="sha384-w447zOpYfw/1Tv/5AK9NfHTlQIqE3RVR6KY62jCyy9zNDgO64cMwGGP1Fj0zJVf5"
    crossorigin="anonymous"></script>
  <script>
    // Initialize in the browser to avoid the CLI's server/client hydration mismatch.
    Redoc.init(JSON.parse(document.getElementById('openapi').textContent), {
      disableGoogleFont: true,
      theme: { typography: { fontFamily: 'Arial, sans-serif', headings: { fontFamily: 'Arial, sans-serif' } } }
    }, document.getElementById('redoc'));
  </script>
</body>
</html>
`, 'utf8');

console.log(`Generated ${output.pathname}`);
